version: '3.8'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: src/Bookify.Api/Dockerfile
    depends_on:
      - bookify-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"

  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql
    ports:
      - "5432:5432"